- name: udpate webservers
  hosts: all
  become: yes
 
  tasks:
  - name: ensure httpd is installed
    package: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: starting apache2
    service: 
        name: apache2
        state: started
    when: ansible_os_family == "Debian"
  - name: enabling the apache2
    service: 
        name: apache2
        enabled: yes
    when: ansible_os_family == "Debian"
  
  - name: ensure httpd is installed
    package: 
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: starting httpd
    service: 
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"
  - name: enabling the  httpd
    service: 
        name: httpd
        enabled: yes
    when: ansible_os_family == "RedHat"

  - name: ensure httpd or apache is running on port 9090
    copy: 
      src: /home/centos/playbooks/static.html
      dest: /var/www/html/page.html






















#  - name: ensure httpd.conf page is updated with 9090
#    copy:
#      src: /home/centos/playbooks/httpd.conf
#      dest: /etc/httpd/conf/httpd.conf
#    when: ansible_os_family == "RedHat"
#  - name: ensure ports.conf page is updated with 9090  
#    copy: 
#      src: /home/centos/playbooks/ports.conf
#      dest: /etc/apache2/ports.conf
#    when: ansible_os_family == "Debian"
#  - name: restart apache2
#    service: 
#        name: apache2
#        state: restarted
#    when: ansible_os_family == "Debian"
#  - name: restarting httpd
#    service: 
#        name: httpd
#        state: restarted
 #   when: ansible_os_family == "RedHat"
