- name: udpate webservers
  hosts: all
  become: yes
  vars: 
    username: Sai Prasad Kyasa
    Pass: Hulk

  tasks:
  - name: ensure httpd is installed
    package: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: starting apache2
    service: 
        name: apache2
        state: started
    when: ansible_os_family == "Debian"
  - name: enabling the apache2
    service: 
        name: apache2
        enabled: yes
    when: ansible_os_family == "Debian"
  
  - name: ensure httpd is installed
    package: 
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: starting httpd
    service: 
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"
  - name: enabling the  httpd
    service: 
        name: httpd
        enabled: yes
    when: ansible_os_family == "RedHat"

  - name: ensure httpd or apache is running on port 9090
    template: 
      src: /home/centos/playbooks/dynamic.j2
      dest: /var/www/html/dynamic.html




