- name: update web servers
  hosts: all
  become: true

  handlers: 
  - name: Restart HTTP
    service: 
      name: httpd
      state: restarted

  tasks: 
  - name: ensure httpd is running on port 80
    copy: 
      src: /home/centos/playbooks/httpd-php.conf
      dest: /etc/httpd/conf/httpd.conf
    notify: 
    - Restart HTTP

  - name: moving date.php in html location
    copy: 
      src: /home/centos/playbooks/date.php
      dest: /var/www/html/

  - name: Ensudre php is installed
    package: 
      name: php
      state: installed
    notify: 
    - Restart HTTP
