- name: udpate webservers
  hosts: all
  become: true

  tasks:
  - name: ensure apache2 is installed
    package: 
      name: apache2
      state: present
  - name: starting apache2
    service: 
        name: apache2
        state: started

  - name: enabling the  apache2
    service: 
        name: apache2
        enabled: yes
